name: Auto Sort & Count Rules

on:
  schedule:
    - cron: '0 0 */3 * *'  # Every day 00:00 UTC
  workflow_dispatch:  # Manual run test

jobs:
  sort-and-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # PAT with repo scope push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run sort & count script
        run: |
          cd autoscript
          python sort_and_count_everything_rules.py --pure-rules

      - name: Check for changes
        run: |
          git config --global user.name "poli0981"
          git config --global user.email "127664709+poli0981@users.noreply.github.com"
          git add .
          git diff --staged --quiet && echo "No changes â€“ skip commit" || (git commit -m "Auto update rules [$(date +'%Y-%m-%d')]" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
