name: Auto Sort & Count Rules

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:  # Manual run test

jobs:
  sort-and-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # PAT with repo scope push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run bash script to sort and count rules
        run: |
          chmod +x ./bash/update.sh
          ./bash/update.sh
        shell: bash